# Generated by Django 4.0.5 on 2022-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Заголовок на главной странице', max_length=200)),
                ('header_image', models.ImageField(help_text='Картинка на главной странице (750x422)', upload_to='portfolio/images/')),
                ('link', models.CharField(default='www', help_text='Ссылка на гитхаб', max_length=300)),
                ('first_image_detail', models.ImageField(help_text='(750x422)', upload_to='portfolio/images/')),
                ('first_image_detail_tumb', models.ImageField(help_text='(750x422)', upload_to='portfolio/images/')),
                ('second_image_detail', models.ImageField(blank=True, help_text='(750x422)', upload_to='portfolio/images/')),
                ('second_image_detail_tumb', models.ImageField(help_text='(750x422)', upload_to='portfolio/images/')),
                ('third_image_detail', models.ImageField(blank=True, help_text='(750x422)', upload_to='portfolio/images/')),
                ('third_image_detail_tumb', models.ImageField(help_text='(750x422)', upload_to='portfolio/images/')),
                ('first_description', models.TextField(help_text='Описание проекта')),
                ('first_description_image', models.ImageField(help_text='Картинка описания проекта (400х400)', upload_to='portfolio/images/')),
                ('second_description', models.TextField(help_text='Что сделал ты')),
                ('second_description_image', models.ImageField(help_text='Картинка действий (400х400)', upload_to='portfolio/images/')),
                ('stack', models.CharField(blank=True, help_text='Стек технологий', max_length=200)),
                ('stack_image1', models.ImageField(blank=True, help_text='Картинка стека (400х400)', upload_to='portfolio/images/')),
            ],
        ),
    ]
