# Generated by Django 4.0.5 on 2022-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Заголовок главной страницы', max_length=200)),
                ('header_image', models.ImageField(height_field=750, help_text='Картинка главной страницы (750x422)', upload_to='portfolio_app/images/', width_field=422)),
                ('title', models.CharField(help_text='Заголовок PopUp окна', max_length=100)),
                ('description', models.TextField(help_text='Описание PopUp окна')),
                ('image', models.ImageField(height_field=900, help_text='Картинка PopUp окна (900x650)', upload_to='portfolio_app/images/', width_field=650)),
                ('stack', models.CharField(help_text='Стек в PopUp окне', max_length=200)),
            ],
        ),
    ]
