# Generated by Django 4.0.5 on 2022-09-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_image_detail',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, help_text='Ссылка на гитхаб', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='second_image_detail',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.CharField(help_text='Стек технологий', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack_image1',
            field=models.ImageField(help_text='Картинка стека (400х400)', upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='third_image_detail',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
    ]
