# Generated by Django 4.0.5 on 2022-09-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_project_first_image_detail_alter_project_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='link_site',
            field=models.CharField(blank=True, help_text='Ссылка на сам сайт', max_length=300, null=True),
        ),
    ]
